common/models/Magazine.php
<?php

namespace common\models;

use yii\mongodb\ActiveRecord;
use yii\data\ActiveDataProvider;
/**
 * Manage magazines
 * 
 * @property \MongoId $_id
 * @property \MongoId $createdBy
 * @property \MongoId $owner
 * @property string $country Country code
 * @property string $title
 * @property string $content
 * @property string $file
 * @property \MongoDate $createdAt
 * @property \MongoDate $updatedAt 
 */
class Magazine extends ActiveRecord {

  public static function collectionName() {
    return 'magazine';
  }

  public function attributes() {
    return [
        '_id', 'createdBy', 'owner', 'country', 'title', 'content', 'file', 'createdAt', 'updatedAt'
    ];
  }

  public function rules() {
    return [
        [['country', 'title', 'content'], 'string'],
        [['file','createdAt', 'updatedAt', 'createdBy', 'owner'], 'safe']
    ];
  }
  
  public function attributeLabels() {
    return [
    ];
  }

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
        'mongoDate' => [
            'class' => '\common\behaviors\mongodb\MongoDate',
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['createdAt', 'updatedAt'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['updatedAt'],
            ],
        ],
        'mongoId' => [
            'class' => '\common\behaviors\mongodb\MongoId',
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['createdBy', 'owner'],
                ActiveRecord::EVENT_BEFORE_UPDATE => ['owner']
            ]
        ]
    ];
  }

  
  /**
   * search data provider
   * @param type $params
   * @return \common\models\ActiveDataProvider
   */
  public function search($params) {
    $query = static::find();
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'pagination' => array('pageSize' => 20)
    ]);

    $this->load($params);

    $where = [];
    foreach ($this->getAttributes() as $key => $value) {
      if ($value != '') {
        if (is_numeric($value)) {
          $value = (int) $value;
        } elseif (is_string($value)) {
          if ($value == 'true' || $value == 'false') {
            $value = $value == 'true' ? true : false;
          } else {
            $value = new \MongoRegex('/' . $value . '/i');
          }
        }
        $where[$key] = $value;
      }
    }
    $query->where($where);

    return $dataProvider;
  }

  /**
   * get owner user
   * @return object
   */
  public function getOwner() {
    return User::findOne(['_id' => $this->owner]);
  }
}

backend/controllers/MagazineController.php
<?php

namespace backend\controllers;

use \Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use common\helpers\File;
use common\models\Magazine;

/**
 * Magazine Controller
 * @author Hoai Tran <tranthanhhoai1990@gmail.com>
 */
class MagazineController extends Controller {

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
        'access' => [
            'class' => AccessControl::className(),
            'ruleConfig' => [
                'class' => '\common\components\AccessRule'
            ],
            'rules' => [
                [
                    'actions' => [
                        'index', 'create', 'update', 'delete'
                    ],
                    'allow' => true,
                    'roles' => [99], //1 free, 2 trial, 3 premium, 99 supper admin
                ],
                [
                    'allow' => false, // Do not have access
                    'roles' => ['?']
                ]
            ]
        ]
    ];
  }

  /**
   * Lists all Magazine models.
   * @return mixed
   */
  public function actionIndex() {
    $model = new Magazine();
    $dataProvider = $model->search(Yii::$app->request->getQueryParams());
    return $this->render('index', compact('model', 'dataProvider'));
  }

  /**
   * Creates a new Magazine model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new Magazine();
    $model->createdBy = Yii::$app->user->id;
    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
      //save file upload
      $file = File::uploadMagazine(UploadedFile::getInstanceByName('file'));
      if ($file['status']) {
        $model->file = $file;
      } elseif ($file['message']) {
        $model->addError('file', $file['message']);
      }
      if ($model->save()) {
        return $this->redirect(['index']);
      }
    }
    return $this->render('create', compact('model'));
  }

  /**
   * Updates an existing Magazine model.
   * If update is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);
    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
      //save file upload
      $file = File::uploadMagazine(UploadedFile::getInstanceByName('file'));      
      if ($file['status']) {
        $model->file = $file;
      } elseif ($file['message']) {
        $model->addError('file', $file['message']);
      }
      if ($model->save()) {
        return $this->redirect(['index']);
      }
    }
    return $this->render('update', compact('model'));
  }

  /**
   * Deletes an existing Magazine model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();
    return $this->redirect(Yii::$app->request->getReferrer() ? Yii::$app->request->getReferrer() : 'index');
  }

  /**
   * Finds the Magazine model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @return Magazine the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = Magazine::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

}

backend/views/magazine/_form.php
<?php

//helper
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//widget
use kartik\widgets\Select2;
use dosamigos\ckeditor\CKEditor;
//model
use common\models\User;
use common\models\Country;
?>

<?php
$form = ActiveForm::begin([
            'options' => ['enctype' => 'multipart/form-data'],
            'layout' => 'horizontal'
        ]);
?>
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <header class="dark">
        <div class="icons">
          <i class="fa fa-check"></i>
        </div>
        <h5>Article Info</h5>
        <!-- .toolbar -->
        <div class="toolbar">
          <nav style="padding: 8px;">
            <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
              <i class="fa fa-minus"></i>
            </a>
          </nav>
        </div><!-- /.toolbar -->
      </header>
      <div class="body">

        <?php
        echo $form->field($model, 'owner')->widget(Select2::classname(), [
            'data' => User:: getAllAsArray()
        ]);
        echo $form->field($model, 'country')->dropDownList(Country::getAllAsArray());
        echo $form->field($model, 'title');

        echo $form->field($model, 'content', [
            'template' => "{label}\n<div class='col-sm-12'>{input}\n{error}</div>"
        ])->widget(CKEditor::className(), [
            'options' => ['rows' => 3],
            'preset' => 'standard'
        ]);
        ?>
        <div class="form-group">
          <label class="control-label col-sm-3">File</label>
          <div class="col-sm-6">
            <?php
            if ($model->file):
              if ($model->file['type'] == 'image'):
                ?>
                <img src="<?= MAGAZINE_URL . $model->file['name']; ?>" height="100"/>
              <?php elseif ($model->file['type'] == 'video'): ?>
                <video width="160" height="120" controls>
                  <source src="<?= MAGAZINE_URL . $model->file['name']?>" type="video/mp4">
                  Your browser does not support the video tag.
                </video>
                <?php
              endif;
            endif;
            ?>
            <?= Html::fileInput('file', '', ['accept' => 'image/*,video/mp4']); ?>
          </div>
        </div>

        <div class="form-actions no-margin-bottom">
          <input type="submit" value="Save" class="btn btn-primary">
        </div>
      </div>
    </div>
  </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/magazine/create.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Magazine', 'url' => ['magazine/index']];
$this->params['breadcrumbs'][] = ['label' => 'Create'];
?>

<?= $this->render('_form', compact('model')); ?>
 

backend/views/magazine/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Country;

$this->params['breadcrumbs'][] = ['label' => 'Magazine'];
$this->params['breadcrumbs'][] = ['label' => '<i class="fa fa-pencil"></i> Add New', 'url' => ['magazine/create']];
?>
<div class="row">
  <div class="col-lg-12">
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
        'layout' => "<div class='responsive-table'>{items}</div>\n
          <div class='row'>
            <div class='col-xs-6'>{summary}</div>
            <div class='col-xs-6'>
              <div class='dataTables_paginate paging_simple_numbers'>
              {pager}
              </div>
            </div>
          </div>",
        'tableOptions' => ['class' => 'table table-striped table-bordered sortableTable responsive-table dataTable'],
        'columns' => [
            [
                'header' => 'Action',
                'options' => ['style' => 'width:50px'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
            ],
            [
              'header'=>'File',
                'format'=>'raw',
              'value'=>function($model){
                if($model->file){
                  if($model->file['type']=='image'){
                    return Html::img(MAGAZINE_URL.$model->file['name'],['width'=>100]);
                  }else{
                    return '<video width="160" height="120" controls>
                  <source src="'.MAGAZINE_URL.$model->file['name'].'" type="video/mp4">
                  Your browser does not support the video tag.
                </video>';
                  }
                }
              }
            ],
            [
                'header' => 'Owner',
                'value' => function($model) {
                  $owner = $model->getOwner();
                  if ($owner) {
                    return $owner->username;
                  }else{
                    return 'deleted';
                  }
                }
            ],
            [
                'attribute' => 'country',
                'filter' => Country::getAllAsArray()
            ],
            'title',
            [
                'attribute' => 'createdAt',
                'filter' => false,
                'value' => function($model) {
                  if (isset($model->createdAt->sec)) {
                    return $model->createdAt->sec;
                  } else {
                    return '';
                  }
                },
                'format' => 'date'
            ]
        ],
    ]);
    ?>
  </div>
</div>

backend/views/magazine/update.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Magezine', 'url' => ['magazine/index']];
$this->params['breadcrumbs'][] = ['label' => 'Update'];
?>

<?= $this->render('_form', compact('model')); ?>
 