backend/controllers/PostController.php
<?php

namespace backend\controllers;

use \Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\ProfileContent;

/**
 * Post Controller
 *
 * @author Hoai Tran <tranthanhhoai1990@gmail.com>
 */
class PostController extends Controller {

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
        'access' => [
            'class' => AccessControl::className(),
            'ruleConfig' => [
                'class' => '\common\components\AccessRule'
            ],
            'rules' => [
                [
                    'actions' => [
                        'index', 'create', 'update', 'delete'
                    ],
                    'allow' => true,
                    'roles' => [99], //1 free, 2 trial, 3 premium, 99 supper admin
                ],
                [
                    'allow' => false, // Do not have access
                    'roles' => ['?']
                ]
            ]
        ]
    ];
  }

  private $_type = '';

  /**
   * check Profile Content type
   */
  public function init() {
    $this->_type = Yii::$app->getRequest()->get('type');
    $type = ['orientation', 'style', 'figure', 'ethnicity', 'other', 'religion', 'upfor',
        'speaking', 'question'];
    if (!$this->_type || !in_array($this->_type, $type)) {
      $this->_type = 'orientation';
    }
  }

  /**
   * Lists all Profile Content models.
   * @return mixed
   */
  public function actionIndex() {
    $model = new ProfileContent();
    $model->type = $this->_type;
    $dataProvider = $model->search(Yii::$app->request->getQueryParams());
    return $this->render('index', compact('model', 'dataProvider'));
  }

  /**
   * Creates a new Profile Content model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new ProfileContent();
    $model->type = $this->_type;
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['index', 'type' => $model->type]);
    } else {
      return $this->render('create', compact('model'));
    }
  }

  /**
   * Updates an existing Profile Content model.
   * If update is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['index', 'type' => $model->type]);
    } else {
      return $this->render('update', compact('model'));
    }
  }

  /**
   * Deletes an existing Profile Content model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();
    return $this->redirect(Yii::$app->request->getReferrer() ? Yii::$app->request->getReferrer() : 'index');
  }

  /**
   * Finds the Profile Content model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @return Profile Content the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = ProfileContent::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

}

backend/views/post/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\helpers\Language;
?>

<?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <header class="dark">
        <div class="icons">
          <i class="fa fa-check"></i>
        </div>
        <h5><?= $model->getAttributeLabel('name'); ?></h5>
        <!-- .toolbar -->
        <div class="toolbar">
          <nav style="padding: 8px;">
            <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
              <i class="fa fa-minus"></i>
            </a>
          </nav>
        </div><!-- /.toolbar -->
      </header>
      <div class="body">
        <?php
        foreach (Language::$languageCodes as $code => $name) :
          ?>
          <?= $form->field($model, 'name[' . $code . ']')->label($name); ?>
          <?php
        endforeach;
        ?>
        <div class="form-actions no-margin-bottom">
          <input type="submit" value="Save" class="btn btn-primary">
        </div>
      </div>
    </div>
  </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/post/create.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Profile ' . $model->type, 'url' => ['post/index', 'type' => $model->type]];
$this->params['breadcrumbs'][] = ['label' => 'Create'];
?>

<?= $this->render('_form', compact('model')); ?>
 

backend/views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->params['breadcrumbs'][] = ['label' => 'Profile '.$model->type];
$this->params['breadcrumbs'][] = ['label' => '<i class="fa fa-pencil"></i> Add New','url'=>['post/create','type'=>$model->type]];
?>
<div class="row">
  <div class="col-lg-12">
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
        'layout' => "<div class='responsive-table'>{items}</div>\n
          <div class='row'>
            <div class='col-xs-6'>{summary}</div>
            <div class='col-xs-6'>
              <div class='dataTables_paginate paging_simple_numbers'>
              {pager}
              </div>
            </div>
          </div>",
        'tableOptions' => ['class' => 'table table-striped table-bordered sortableTable responsive-table dataTable'],
        'columns' => [
            [
                'header' => 'Action',
                'options' => ['style' => 'width:50px'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function($model) {
                  if (is_array($model->name)) {
                    foreach ($model->name as $key => $value) {
                      if ($key == 'en') {
                        return $value;
                      }
                    }
                  }
                }
            ],
            [
                'attribute' => 'createdAt',
                'filter' => false,
                'value' => function($model) {
                  if (isset($model->createdAt->sec)) {
                    return $model->createdAt->sec;
                  } else {
                    return '';
                  }
                },
                'format' => 'date'
            ]
        ],
    ]);
    ?>
  </div>
</div>

backend/views/post/update.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Profile '.$model->type, 'url' => ['post/index', 'type' => $model->type]];
$this->params['breadcrumbs'][] = ['label' => 'Update'];
?>

<?= $this->render('_form', compact('model')); ?>
 