common/models/Banner.php
<?php

namespace common\models;

use yii\mongodb\ActiveRecord;
use yii\data\ActiveDataProvider;

/**
 * Banner model
 * @property \MongoId $_id
 * @property \MongoId $createdBy
 * @property string $country Country code
 * @property array $file
 * @property string $url
 * @property \MongoDate $startDate
 * @property \MongoDate $endDate
 * @property \MongoDate $createAt
 * @property int $status
 * 
 * @author Hoai Tran <tranthanhhoai1990@gmail.com>
 */
class Banner extends ActiveRecord {

  /**
   * @return string the name of the index associated with this ActiveRecord class.
   */
  public static function collectionName() {
    return 'banners';
  }

  /**
   * @return array list of attribute names.
   */
  public function attributes() {
    return [
        '_id', 'country', 'file', 'url', 'startDate', 'endDate', 'createdBy', 'createdAt'
    ];
  }

  /**
   * define rule for invoice
   * @return type
   */
  public function rules() {
    return [
        [['url', 'startDate', 'endDate'], 'required'],
        [['country', 'url'], 'string'],
        [['startDate', 'endDate'], 'dateValidator'],
        [['file', 'createdBy', 'createdAt', 'startDate', 'endDate'], 'safe']
    ];
  }

  /**
   * Convert string to int for mongodb
   * @param type $attr
   * @param type $params
   */
  public function converNumber($attr, $params) {
    if (!$this->getErrors() && $this->{$attr}) {
      $this->{$attr} = (int) $this->{$attr};
    }
  }

  /**
   * validator date format
   * convert date to mongo date
   * @param type $attr
   */
  public function dateValidator($attr) {
    if (!$this->getErrors() && !$this->{$attr} instanceof \MongoDate) {
      if (!preg_match('/^(?:20|19)[0-9]{2}\-(?:0[1-9]|1[012])\-(?:0[1-9]|[12][0-9]|3[01])$/', $this->{$attr})) {
        $this->addError($attr, 'Date format must be yyyy-mm-dd');
      } else {
        $this->{$attr} = new \MongoDate(strtotime($this->{$attr}));
      }
    }
  }

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
        'mongoDate' => [
            'class' => '\common\behaviors\mongodb\MongoDate',
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['createdAt'],
            ],
        ],
        'mongoId' => [
            'class' => '\common\behaviors\mongodb\MongoId',
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => ['createdBy'],
            ]
        ]
    ];
  }

  /**
   * search data provider
   * @param type $params
   * @return \common\models\ActiveDataProvider
   */
  public function search($params) {
    $query = static::find();
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'pagination' => array('pageSize' => 20)
    ]);

    $this->load($params);

    $where = [];
    foreach ($this->getAttributes() as $key => $value) {
      if ($value != '') {
        if (is_numeric($value)) {
          $value = (int) $value;
        } elseif (is_string($value)) {
          if ($value == 'true' || $value == 'false') {
            $value = $value == 'true' ? true : false;
          } else {
            $value = new \MongoRegex('/' . $value . '/i');
          }
        }
        $where[$key] = $value;
      }
    }
    $query->where($where);

    return $dataProvider;
  }

  /**
   * conver date format
   * @param type $format
   */
  public function formatDate($format = 'Y-m-d') {
    if (isset($this->startDate->sec)) {
      $this->startDate = date($format, $this->startDate->sec);
    }
    if (isset($this->endDate->sec)) {
      $this->endDate = date($format, $this->endDate->sec);
    }
  }
}

backend/controllers/BannerController.php
<?php

namespace backend\controllers;

use \Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use common\helpers\File;
use common\models\Banner;

/**
 * Banner Controller
 * @author Hoai Tran <tranthanhhoai1990@gmail.com>
 */
class BannerController extends Controller {

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
        'access' => [
            'class' => AccessControl::className(),
            'ruleConfig' => [
                'class' => '\common\components\AccessRule'
            ],
            'rules' => [
                [
                    'actions' => [
                        'index', 'create', 'update', 'delete'
                    ],
                    'allow' => true,
                    'roles' => [99], //1 free, 2 trial, 3 premium, 99 supper admin
                ],
                [
                    'allow' => false, // Do not have access
                    'roles' => ['?']
                ]
            ]
        ]
    ];
  }

  /**
   * Lists all Banner models.
   * @return mixed
   */
  public function actionIndex() {
    $model = new Banner();
    $dataProvider = $model->search(Yii::$app->request->getQueryParams());
    return $this->render('index', compact('model', 'dataProvider'));
  }

  /**
   * Creates a new Banner model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate() {
    $model = new Banner();
    $model->createdBy = Yii::$app->user->id;
    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
      //save file upload
      $file = File::upload(UploadedFile::getInstanceByName('file'), BANNER_PATH, true); 
      if ($file['status']) {
        $model->file = $file;
      } elseif ($file['message']) {
        $model->addError('file', $file['message']);
      }
      if (!$model->getErrors() && $model->save()) {
        return $this->redirect(['index']);
      }
    }
    return $this->render('create', compact('model'));
  }

  /**
   * Updates an existing Banner model.
   * If update is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionUpdate($id) {
    $model = $this->findModel($id);
    $model->formatDate();
    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
      //save file upload
      $file = File::upload(UploadedFile::getInstanceByName('file'), BANNER_PATH);      
      if ($file['status']) {
        $model->file = $file;
      } elseif ($file['message']) {
        $model->addError('file', $file['message']);
      }
      if ($model->save()) {
        return $this->redirect(['index']);
      }
    }
    return $this->render('update', compact('model'));
  }

  /**
   * Deletes an existing Banner model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param string $id Page PK
   * @return mixed
   */
  public function actionDelete($id) {
    $this->findModel($id)->delete();
    return $this->redirect(Yii::$app->request->getReferrer() ? Yii::$app->request->getReferrer() : 'index');
  }

  /**
   * Finds the Banner model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @return Banner the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id) {
    if (($model = Banner::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

}

backend/views/banner/_form.php
<?php

//helper
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//widget
use kartik\widgets\DatePicker;
//model
use common\models\User;
use common\models\Country;
?>

<?php
$form = ActiveForm::begin([
            'options' => ['enctype' => 'multipart/form-data'],
            'layout' => 'horizontal'
        ]);
?>
<div class="row">
  <div class="col-lg-12">
    <div class="box">
      <header class="dark">
        <div class="icons">
          <i class="fa fa-check"></i>
        </div>
        <h5>Banner Info</h5>
        <!-- .toolbar -->
        <div class="toolbar">
          <nav style="padding: 8px;">
            <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
              <i class="fa fa-minus"></i>
            </a>
          </nav>
        </div><!-- /.toolbar -->
      </header>
      <div class="body">

        <?php
        echo $form->field($model, 'country')->dropDownList(Country::getAllAsArray());
        echo $form->field($model, 'url');
        echo $form->field($model, 'startDate')->widget(DatePicker::classname(), [
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]
        ]);
        echo $form->field($model, 'endDate')->widget(DatePicker::classname(), [
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]
        ]);
        ?>
        <div class="form-group">
          <label class="control-label col-sm-3">File</label>
          <div class="col-sm-6">
            <?php
            if ($model->file):
              if ($model->file['type'] == 'image'):
                ?>
                <img src="<?= BANNER_URL . $model->file['name']; ?>" height="100"/>
                <?php
              endif;
            endif;
            ?>
            <?= Html::fileInput('file', '', ['accept' => 'image/*']); ?>
            <?= Html::error($model, 'file') ?>
          </div>
        </div>

        <div class="form-actions no-margin-bottom">
          <input type="submit" value="Save" class="btn btn-primary">
        </div>
      </div>
    </div>
  </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/banner/create.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Banners', 'url' => ['banner/index']];
$this->params['breadcrumbs'][] = ['label' => 'Create'];
?>

<?= $this->render('_form', compact('model')); ?>
 

backend/views/banner/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Country;

$this->params['breadcrumbs'][] = ['label' => 'Banners'];
$this->params['breadcrumbs'][] = ['label' => '<i class="fa fa-pencil"></i> Add New', 'url' => ['banner/create']];
?>
<div class="row">
  <div class="col-lg-12">
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
        'layout' => "<div class='responsive-table'>{items}</div>\n
          <div class='row'>
            <div class='col-xs-6'>{summary}</div>
            <div class='col-xs-6'>
              <div class='dataTables_paginate paging_simple_numbers'>
              {pager}
              </div>
            </div>
          </div>",
        'tableOptions' => ['class' => 'table table-striped table-bordered sortableTable responsive-table dataTable'],
        'columns' => [
            [
                'header' => 'Action',
                'options' => ['style' => 'width:50px'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}{delete}',
            ],
            [
              'header'=>'File',
                'format'=>'raw',
              'value'=>function($model){
                if($model->file){
                  if($model->file['type']=='image'){
                    return Html::img(BANNER_URL.$model->file['name'],['width'=>100]);
                  }
                }
              }
            ],
            [
                'attribute' => 'country',
                'filter' => Country::getAllAsArray()
            ],
            'url',
            [
                'attribute' => 'startDate',
                'filter' => false,
                'value' => function($model) {
                  if (isset($model->startDate->sec)) {
                    return $model->startDate->sec;
                  } else {
                    return '';
                  }
                },
                'format' => ['date', 'Y-m-d']
            ],
            [
                'attribute' => 'endDate',
                'filter' => false,
                'value' => function($model) {
                  if (isset($model->endDate->sec)) {
                    return $model->endDate->sec;
                  } else {
                    return '';
                  }
                },
                'format' => ['date', 'Y-m-d']
            ],
            [
                'attribute' => 'createdAt',
                'filter' => false,
                'value' => function($model) {
                  if (isset($model->createdAt->sec)) {
                    return $model->createdAt->sec;
                  } else {
                    return '';
                  }
                },
                'format' => 'date'
            ]
        ],
    ]);
    ?>
  </div>
</div>

backend/views/banner/update.php
<?php

$this->params['breadcrumbs'][] = ['label' => 'Banners', 'url' => ['banner/index']];
$this->params['breadcrumbs'][] = ['label' => 'Update'];
?>

<?= $this->render('_form', compact('model')); ?>
 